# Generated by Django 4.1.2 on 2022-10-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonaI',
            new_name='Persona',
        ),
    ]
